//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_KS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://turkpara.com.tr/", ConfigurationName="TP_KS.TP_KSSoap")]
    public interface TP_KSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Kart_Ekle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TP_KS.ST_KS_Kart_Ekle KS_Kart_Ekle(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Sahibi, string KK_No, string KK_SK_Ay, string KK_SK_Yil, string KK_Kart_Adi, string KK_Islem_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Kart_Ekle", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_KS.ST_KS_Kart_Ekle> KS_Kart_EkleAsync(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Sahibi, string KK_No, string KK_SK_Ay, string KK_SK_Yil, string KK_Kart_Adi, string KK_Islem_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Kart_Liste_Pagination", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TP_KS.ST_KS_Kart_Liste KS_Kart_Liste_Pagination(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID, string sayfa_Sayi, string sayfa_index);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Kart_Liste_Pagination", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_KS.ST_KS_Kart_Liste> KS_Kart_Liste_PaginationAsync(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID, string sayfa_Sayi, string sayfa_index);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Kart_Liste", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TP_KS.ST_KS_Kart_Liste KS_Kart_Liste(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Kart_Liste", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_KS.ST_KS_Kart_Liste> KS_Kart_ListeAsync(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Kart_Sil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TP_KS.ST_Sonuc KS_Kart_Sil(TP_KS.ST_WS_Guvenlik G, string KS_GUID, string KK_Islem_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Kart_Sil", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_KS.ST_Sonuc> KS_Kart_SilAsync(TP_KS.ST_WS_Guvenlik G, string KS_GUID, string KK_Islem_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Tahsilat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TP_KS.ST_TP_Islem_Odeme KS_Tahsilat(
                    TP_KS.ST_WS_Guvenlik G, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Tahsilat", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_KS.ST_TP_Islem_Odeme> KS_TahsilatAsync(
                    TP_KS.ST_WS_Guvenlik G, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Tahsilat_Colendi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TP_KS.ST_TP_Islem_Odeme KS_Tahsilat_Colendi(
                    TP_KS.ST_WS_Guvenlik G, 
                    string MGUID, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://turkpara.com.tr/KS_Tahsilat_Colendi", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_KS.ST_TP_Islem_Odeme> KS_Tahsilat_ColendiAsync(
                    TP_KS.ST_WS_Guvenlik G, 
                    string MGUID, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpara.com.tr/")]
    public partial class ST_WS_Guvenlik
    {
        
        private int cLIENT_CODEField;
        
        private string cLIENT_USERNAMEField;
        
        private string cLIENT_PASSWORDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CLIENT_CODE
        {
            get
            {
                return this.cLIENT_CODEField;
            }
            set
            {
                this.cLIENT_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CLIENT_USERNAME
        {
            get
            {
                return this.cLIENT_USERNAMEField;
            }
            set
            {
                this.cLIENT_USERNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CLIENT_PASSWORD
        {
            get
            {
                return this.cLIENT_PASSWORDField;
            }
            set
            {
                this.cLIENT_PASSWORDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpara.com.tr/")]
    public partial class ST_TP_Islem_Odeme
    {
        
        private long islem_IDField;
        
        private string uCD_URLField;
        
        private string sonucField;
        
        private string sonuc_StrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Islem_ID
        {
            get
            {
                return this.islem_IDField;
            }
            set
            {
                this.islem_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UCD_URL
        {
            get
            {
                return this.uCD_URLField;
            }
            set
            {
                this.uCD_URLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sonuc_Str
        {
            get
            {
                return this.sonuc_StrField;
            }
            set
            {
                this.sonuc_StrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpara.com.tr/")]
    public partial class ST_Sonuc
    {
        
        private int sonucField;
        
        private string sonuc_StrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sonuc_Str
        {
            get
            {
                return this.sonuc_StrField;
            }
            set
            {
                this.sonuc_StrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpara.com.tr/")]
    public partial class ST_KS_Kart_Liste
    {
        
        private int sonucField;
        
        private string sonuc_StrField;
        
        private ST_KS_Kart_ListeDT_Bilgi dT_BilgiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sonuc_Str
        {
            get
            {
                return this.sonuc_StrField;
            }
            set
            {
                this.sonuc_StrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ST_KS_Kart_ListeDT_Bilgi DT_Bilgi
        {
            get
            {
                return this.dT_BilgiField;
            }
            set
            {
                this.dT_BilgiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://turkpara.com.tr/")]
    public partial class ST_KS_Kart_ListeDT_Bilgi
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpara.com.tr/")]
    public partial class ST_KS_Kart_Ekle
    {
        
        private int sonucField;
        
        private string sonuc_StrField;
        
        private string kS_GUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Sonuc
        {
            get
            {
                return this.sonucField;
            }
            set
            {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sonuc_Str
        {
            get
            {
                return this.sonuc_StrField;
            }
            set
            {
                this.sonuc_StrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string KS_GUID
        {
            get
            {
                return this.kS_GUIDField;
            }
            set
            {
                this.kS_GUIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface TP_KSSoapChannel : TP_KS.TP_KSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TP_KSSoapClient : System.ServiceModel.ClientBase<TP_KS.TP_KSSoap>, TP_KS.TP_KSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TP_KSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TP_KSSoapClient.GetBindingForEndpoint(endpointConfiguration), TP_KSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TP_KSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TP_KSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TP_KSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TP_KSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TP_KSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TP_KS.ST_KS_Kart_Ekle KS_Kart_Ekle(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Sahibi, string KK_No, string KK_SK_Ay, string KK_SK_Yil, string KK_Kart_Adi, string KK_Islem_ID)
        {
            return base.Channel.KS_Kart_Ekle(G, GUID, KK_Sahibi, KK_No, KK_SK_Ay, KK_SK_Yil, KK_Kart_Adi, KK_Islem_ID);
        }
        
        public System.Threading.Tasks.Task<TP_KS.ST_KS_Kart_Ekle> KS_Kart_EkleAsync(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Sahibi, string KK_No, string KK_SK_Ay, string KK_SK_Yil, string KK_Kart_Adi, string KK_Islem_ID)
        {
            return base.Channel.KS_Kart_EkleAsync(G, GUID, KK_Sahibi, KK_No, KK_SK_Ay, KK_SK_Yil, KK_Kart_Adi, KK_Islem_ID);
        }
        
        public TP_KS.ST_KS_Kart_Liste KS_Kart_Liste_Pagination(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID, string sayfa_Sayi, string sayfa_index)
        {
            return base.Channel.KS_Kart_Liste_Pagination(G, GUID, KK_Kart_Adi, KK_Islem_ID, sayfa_Sayi, sayfa_index);
        }
        
        public System.Threading.Tasks.Task<TP_KS.ST_KS_Kart_Liste> KS_Kart_Liste_PaginationAsync(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID, string sayfa_Sayi, string sayfa_index)
        {
            return base.Channel.KS_Kart_Liste_PaginationAsync(G, GUID, KK_Kart_Adi, KK_Islem_ID, sayfa_Sayi, sayfa_index);
        }
        
        public TP_KS.ST_KS_Kart_Liste KS_Kart_Liste(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID)
        {
            return base.Channel.KS_Kart_Liste(G, GUID, KK_Kart_Adi, KK_Islem_ID);
        }
        
        public System.Threading.Tasks.Task<TP_KS.ST_KS_Kart_Liste> KS_Kart_ListeAsync(TP_KS.ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID)
        {
            return base.Channel.KS_Kart_ListeAsync(G, GUID, KK_Kart_Adi, KK_Islem_ID);
        }
        
        public TP_KS.ST_Sonuc KS_Kart_Sil(TP_KS.ST_WS_Guvenlik G, string KS_GUID, string KK_Islem_ID)
        {
            return base.Channel.KS_Kart_Sil(G, KS_GUID, KK_Islem_ID);
        }
        
        public System.Threading.Tasks.Task<TP_KS.ST_Sonuc> KS_Kart_SilAsync(TP_KS.ST_WS_Guvenlik G, string KS_GUID, string KK_Islem_ID)
        {
            return base.Channel.KS_Kart_SilAsync(G, KS_GUID, KK_Islem_ID);
        }
        
        public TP_KS.ST_TP_Islem_Odeme KS_Tahsilat(
                    TP_KS.ST_WS_Guvenlik G, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID)
        {
            return base.Channel.KS_Tahsilat(G, GUID, KS_GUID, CVV, KK_Sahibi_GSM, Hata_URL, Basarili_URL, Siparis_ID, Siparis_Aciklama, Taksit, Islem_Tutar, Toplam_Tutar, Islem_Guvenlik_Tip, Islem_ID, IPAdr, Ref_URL, Data1, Data2, Data3, Data4, KK_Islem_ID);
        }
        
        public System.Threading.Tasks.Task<TP_KS.ST_TP_Islem_Odeme> KS_TahsilatAsync(
                    TP_KS.ST_WS_Guvenlik G, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID)
        {
            return base.Channel.KS_TahsilatAsync(G, GUID, KS_GUID, CVV, KK_Sahibi_GSM, Hata_URL, Basarili_URL, Siparis_ID, Siparis_Aciklama, Taksit, Islem_Tutar, Toplam_Tutar, Islem_Guvenlik_Tip, Islem_ID, IPAdr, Ref_URL, Data1, Data2, Data3, Data4, KK_Islem_ID);
        }
        
        public TP_KS.ST_TP_Islem_Odeme KS_Tahsilat_Colendi(
                    TP_KS.ST_WS_Guvenlik G, 
                    string MGUID, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID)
        {
            return base.Channel.KS_Tahsilat_Colendi(G, MGUID, GUID, KS_GUID, CVV, KK_Sahibi_GSM, Hata_URL, Basarili_URL, Siparis_ID, Siparis_Aciklama, Taksit, Islem_Tutar, Toplam_Tutar, Islem_Guvenlik_Tip, Islem_ID, IPAdr, Ref_URL, Data1, Data2, Data3, Data4, KK_Islem_ID);
        }
        
        public System.Threading.Tasks.Task<TP_KS.ST_TP_Islem_Odeme> KS_Tahsilat_ColendiAsync(
                    TP_KS.ST_WS_Guvenlik G, 
                    string MGUID, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID)
        {
            return base.Channel.KS_Tahsilat_ColendiAsync(G, MGUID, GUID, KS_GUID, CVV, KK_Sahibi_GSM, Hata_URL, Basarili_URL, Siparis_ID, Siparis_Aciklama, Taksit, Islem_Tutar, Toplam_Tutar, Islem_Guvenlik_Tip, Islem_ID, IPAdr, Ref_URL, Data1, Data2, Data3, Data4, KK_Islem_ID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TP_KSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TP_KSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TP_KSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://test-dmz.param.com.tr/out.ws/service_ks.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TP_KSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://test-dmz.param.com.tr/out.ws/service_ks.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TP_KSSoap,
            
            TP_KSSoap12,
        }
    }
}
