
package org.example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * TURK Elektronik Para A.\u015e.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TurkPos_x0020_WS_x0020_TEST", targetNamespace = "https://turkpos.com.tr/", wsdlLocation = "file:/C:/java/file.xml")
public class TurkPosX0020WSX0020TEST
    extends Service
{

    private final static URL TURKPOSX0020WSX0020TEST_WSDL_LOCATION;
    private final static WebServiceException TURKPOSX0020WSX0020TEST_EXCEPTION;
    private final static QName TURKPOSX0020WSX0020TEST_QNAME = new QName("https://turkpos.com.tr/", "TurkPos_x0020_WS_x0020_TEST");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/java/file.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TURKPOSX0020WSX0020TEST_WSDL_LOCATION = url;
        TURKPOSX0020WSX0020TEST_EXCEPTION = e;
    }

    public TurkPosX0020WSX0020TEST() {
        super(__getWsdlLocation(), TURKPOSX0020WSX0020TEST_QNAME);
    }

    public TurkPosX0020WSX0020TEST(WebServiceFeature... features) {
        super(__getWsdlLocation(), TURKPOSX0020WSX0020TEST_QNAME, features);
    }

    public TurkPosX0020WSX0020TEST(URL wsdlLocation) {
        super(wsdlLocation, TURKPOSX0020WSX0020TEST_QNAME);
    }

    public TurkPosX0020WSX0020TEST(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TURKPOSX0020WSX0020TEST_QNAME, features);
    }

    public TurkPosX0020WSX0020TEST(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TurkPosX0020WSX0020TEST(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TurkPosX0020WSX0020TESTSoap
     */
    @WebEndpoint(name = "TurkPos_x0020_WS_x0020_TESTSoap")
    public TurkPosX0020WSX0020TESTSoap getTurkPosX0020WSX0020TESTSoap() {
        return super.getPort(new QName("https://turkpos.com.tr/", "TurkPos_x0020_WS_x0020_TESTSoap"), TurkPosX0020WSX0020TESTSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TurkPosX0020WSX0020TESTSoap
     */
    @WebEndpoint(name = "TurkPos_x0020_WS_x0020_TESTSoap")
    public TurkPosX0020WSX0020TESTSoap getTurkPosX0020WSX0020TESTSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://turkpos.com.tr/", "TurkPos_x0020_WS_x0020_TESTSoap"), TurkPosX0020WSX0020TESTSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TURKPOSX0020WSX0020TEST_EXCEPTION!= null) {
            throw TURKPOSX0020WSX0020TEST_EXCEPTION;
        }
        return TURKPOSX0020WSX0020TEST_WSDL_LOCATION;
    }

}
