//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace com.turkpos.apidocs.tr.com.ew.dmzws1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TP_KSSoap", Namespace="https://turkpara.com.tr/")]
    public partial class TP_KS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback KS_Kart_EkleOperationCompleted;
        
        private System.Threading.SendOrPostCallback KS_Kart_ListeOperationCompleted;
        
        private System.Threading.SendOrPostCallback KS_Kart_SilOperationCompleted;
        
        private System.Threading.SendOrPostCallback KS_TahsilatOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TP_KS() {
            this.Url = global::com.turkpos.apidocs.Properties.Settings.Default.com_turkpos_apidocs_tr_com_ew_dmzws1_TP_KS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event KS_Kart_EkleCompletedEventHandler KS_Kart_EkleCompleted;
        
        /// <remarks/>
        public event KS_Kart_ListeCompletedEventHandler KS_Kart_ListeCompleted;
        
        /// <remarks/>
        public event KS_Kart_SilCompletedEventHandler KS_Kart_SilCompleted;
        
        /// <remarks/>
        public event KS_TahsilatCompletedEventHandler KS_TahsilatCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpara.com.tr/KS_Kart_Ekle", RequestNamespace="https://turkpara.com.tr/", ResponseNamespace="https://turkpara.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_KS_Kart_Ekle KS_Kart_Ekle(ST_WS_Guvenlik G, string GUID, string KK_Sahibi, string KK_No, string KK_SK_Ay, string KK_SK_Yil, string KK_Kart_Adi, string KK_Islem_ID) {
            object[] results = this.Invoke("KS_Kart_Ekle", new object[] {
                        G,
                        GUID,
                        KK_Sahibi,
                        KK_No,
                        KK_SK_Ay,
                        KK_SK_Yil,
                        KK_Kart_Adi,
                        KK_Islem_ID});
            return ((ST_KS_Kart_Ekle)(results[0]));
        }
        
        /// <remarks/>
        public void KS_Kart_EkleAsync(ST_WS_Guvenlik G, string GUID, string KK_Sahibi, string KK_No, string KK_SK_Ay, string KK_SK_Yil, string KK_Kart_Adi, string KK_Islem_ID) {
            this.KS_Kart_EkleAsync(G, GUID, KK_Sahibi, KK_No, KK_SK_Ay, KK_SK_Yil, KK_Kart_Adi, KK_Islem_ID, null);
        }
        
        /// <remarks/>
        public void KS_Kart_EkleAsync(ST_WS_Guvenlik G, string GUID, string KK_Sahibi, string KK_No, string KK_SK_Ay, string KK_SK_Yil, string KK_Kart_Adi, string KK_Islem_ID, object userState) {
            if ((this.KS_Kart_EkleOperationCompleted == null)) {
                this.KS_Kart_EkleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKS_Kart_EkleOperationCompleted);
            }
            this.InvokeAsync("KS_Kart_Ekle", new object[] {
                        G,
                        GUID,
                        KK_Sahibi,
                        KK_No,
                        KK_SK_Ay,
                        KK_SK_Yil,
                        KK_Kart_Adi,
                        KK_Islem_ID}, this.KS_Kart_EkleOperationCompleted, userState);
        }
        
        private void OnKS_Kart_EkleOperationCompleted(object arg) {
            if ((this.KS_Kart_EkleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KS_Kart_EkleCompleted(this, new KS_Kart_EkleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpara.com.tr/KS_Kart_Liste", RequestNamespace="https://turkpara.com.tr/", ResponseNamespace="https://turkpara.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_KS_Kart_Liste KS_Kart_Liste(ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID) {
            object[] results = this.Invoke("KS_Kart_Liste", new object[] {
                        G,
                        GUID,
                        KK_Kart_Adi,
                        KK_Islem_ID});
            return ((ST_KS_Kart_Liste)(results[0]));
        }
        
        /// <remarks/>
        public void KS_Kart_ListeAsync(ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID) {
            this.KS_Kart_ListeAsync(G, GUID, KK_Kart_Adi, KK_Islem_ID, null);
        }
        
        /// <remarks/>
        public void KS_Kart_ListeAsync(ST_WS_Guvenlik G, string GUID, string KK_Kart_Adi, string KK_Islem_ID, object userState) {
            if ((this.KS_Kart_ListeOperationCompleted == null)) {
                this.KS_Kart_ListeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKS_Kart_ListeOperationCompleted);
            }
            this.InvokeAsync("KS_Kart_Liste", new object[] {
                        G,
                        GUID,
                        KK_Kart_Adi,
                        KK_Islem_ID}, this.KS_Kart_ListeOperationCompleted, userState);
        }
        
        private void OnKS_Kart_ListeOperationCompleted(object arg) {
            if ((this.KS_Kart_ListeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KS_Kart_ListeCompleted(this, new KS_Kart_ListeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpara.com.tr/KS_Kart_Sil", RequestNamespace="https://turkpara.com.tr/", ResponseNamespace="https://turkpara.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_Sonuc KS_Kart_Sil(ST_WS_Guvenlik G, string KS_GUID, string KK_Islem_ID) {
            object[] results = this.Invoke("KS_Kart_Sil", new object[] {
                        G,
                        KS_GUID,
                        KK_Islem_ID});
            return ((ST_Sonuc)(results[0]));
        }
        
        /// <remarks/>
        public void KS_Kart_SilAsync(ST_WS_Guvenlik G, string KS_GUID, string KK_Islem_ID) {
            this.KS_Kart_SilAsync(G, KS_GUID, KK_Islem_ID, null);
        }
        
        /// <remarks/>
        public void KS_Kart_SilAsync(ST_WS_Guvenlik G, string KS_GUID, string KK_Islem_ID, object userState) {
            if ((this.KS_Kart_SilOperationCompleted == null)) {
                this.KS_Kart_SilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKS_Kart_SilOperationCompleted);
            }
            this.InvokeAsync("KS_Kart_Sil", new object[] {
                        G,
                        KS_GUID,
                        KK_Islem_ID}, this.KS_Kart_SilOperationCompleted, userState);
        }
        
        private void OnKS_Kart_SilOperationCompleted(object arg) {
            if ((this.KS_Kart_SilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KS_Kart_SilCompleted(this, new KS_Kart_SilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://turkpara.com.tr/KS_Tahsilat", RequestNamespace="https://turkpara.com.tr/", ResponseNamespace="https://turkpara.com.tr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ST_TP_Islem_Odeme KS_Tahsilat(
                    ST_WS_Guvenlik G, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID) {
            object[] results = this.Invoke("KS_Tahsilat", new object[] {
                        G,
                        GUID,
                        KS_GUID,
                        CVV,
                        KK_Sahibi_GSM,
                        Hata_URL,
                        Basarili_URL,
                        Siparis_ID,
                        Siparis_Aciklama,
                        Taksit,
                        Islem_Tutar,
                        Toplam_Tutar,
                        Islem_Guvenlik_Tip,
                        Islem_ID,
                        IPAdr,
                        Ref_URL,
                        Data1,
                        Data2,
                        Data3,
                        Data4,
                        KK_Islem_ID});
            return ((ST_TP_Islem_Odeme)(results[0]));
        }
        
        /// <remarks/>
        public void KS_TahsilatAsync(
                    ST_WS_Guvenlik G, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID) {
            this.KS_TahsilatAsync(G, GUID, KS_GUID, CVV, KK_Sahibi_GSM, Hata_URL, Basarili_URL, Siparis_ID, Siparis_Aciklama, Taksit, Islem_Tutar, Toplam_Tutar, Islem_Guvenlik_Tip, Islem_ID, IPAdr, Ref_URL, Data1, Data2, Data3, Data4, KK_Islem_ID, null);
        }
        
        /// <remarks/>
        public void KS_TahsilatAsync(
                    ST_WS_Guvenlik G, 
                    string GUID, 
                    string KS_GUID, 
                    string CVV, 
                    string KK_Sahibi_GSM, 
                    string Hata_URL, 
                    string Basarili_URL, 
                    string Siparis_ID, 
                    string Siparis_Aciklama, 
                    int Taksit, 
                    string Islem_Tutar, 
                    string Toplam_Tutar, 
                    string Islem_Guvenlik_Tip, 
                    string Islem_ID, 
                    string IPAdr, 
                    string Ref_URL, 
                    string Data1, 
                    string Data2, 
                    string Data3, 
                    string Data4, 
                    string KK_Islem_ID, 
                    object userState) {
            if ((this.KS_TahsilatOperationCompleted == null)) {
                this.KS_TahsilatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKS_TahsilatOperationCompleted);
            }
            this.InvokeAsync("KS_Tahsilat", new object[] {
                        G,
                        GUID,
                        KS_GUID,
                        CVV,
                        KK_Sahibi_GSM,
                        Hata_URL,
                        Basarili_URL,
                        Siparis_ID,
                        Siparis_Aciklama,
                        Taksit,
                        Islem_Tutar,
                        Toplam_Tutar,
                        Islem_Guvenlik_Tip,
                        Islem_ID,
                        IPAdr,
                        Ref_URL,
                        Data1,
                        Data2,
                        Data3,
                        Data4,
                        KK_Islem_ID}, this.KS_TahsilatOperationCompleted, userState);
        }
        
        private void OnKS_TahsilatOperationCompleted(object arg) {
            if ((this.KS_TahsilatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KS_TahsilatCompleted(this, new KS_TahsilatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpara.com.tr/")]
    public partial class ST_WS_Guvenlik {
        
        private int cLIENT_CODEField;
        
        private string cLIENT_USERNAMEField;
        
        private string cLIENT_PASSWORDField;
        
        /// <remarks/>
        public int CLIENT_CODE {
            get {
                return this.cLIENT_CODEField;
            }
            set {
                this.cLIENT_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string CLIENT_USERNAME {
            get {
                return this.cLIENT_USERNAMEField;
            }
            set {
                this.cLIENT_USERNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string CLIENT_PASSWORD {
            get {
                return this.cLIENT_PASSWORDField;
            }
            set {
                this.cLIENT_PASSWORDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpara.com.tr/")]
    public partial class ST_TP_Islem_Odeme {
        
        private long islem_IDField;
        
        private string uCD_URLField;
        
        private string sonucField;
        
        private string sonuc_StrField;
        
        /// <remarks/>
        public long Islem_ID {
            get {
                return this.islem_IDField;
            }
            set {
                this.islem_IDField = value;
            }
        }
        
        /// <remarks/>
        public string UCD_URL {
            get {
                return this.uCD_URLField;
            }
            set {
                this.uCD_URLField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc_Str {
            get {
                return this.sonuc_StrField;
            }
            set {
                this.sonuc_StrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpara.com.tr/")]
    public partial class ST_Sonuc {
        
        private int sonucField;
        
        private string sonuc_StrField;
        
        /// <remarks/>
        public int Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc_Str {
            get {
                return this.sonuc_StrField;
            }
            set {
                this.sonuc_StrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpara.com.tr/")]
    public partial class ST_KS_Kart_Liste {
        
        private int sonucField;
        
        private string sonuc_StrField;
        
        private System.Data.DataTable dT_BilgiField;
        
        /// <remarks/>
        public int Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc_Str {
            get {
                return this.sonuc_StrField;
            }
            set {
                this.sonuc_StrField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable DT_Bilgi {
            get {
                return this.dT_BilgiField;
            }
            set {
                this.dT_BilgiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://turkpara.com.tr/")]
    public partial class ST_KS_Kart_Ekle {
        
        private int sonucField;
        
        private string sonuc_StrField;
        
        private string kS_GUIDField;
        
        /// <remarks/>
        public int Sonuc {
            get {
                return this.sonucField;
            }
            set {
                this.sonucField = value;
            }
        }
        
        /// <remarks/>
        public string Sonuc_Str {
            get {
                return this.sonuc_StrField;
            }
            set {
                this.sonuc_StrField = value;
            }
        }
        
        /// <remarks/>
        public string KS_GUID {
            get {
                return this.kS_GUIDField;
            }
            set {
                this.kS_GUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void KS_Kart_EkleCompletedEventHandler(object sender, KS_Kart_EkleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KS_Kart_EkleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KS_Kart_EkleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_KS_Kart_Ekle Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_KS_Kart_Ekle)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void KS_Kart_ListeCompletedEventHandler(object sender, KS_Kart_ListeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KS_Kart_ListeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KS_Kart_ListeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_KS_Kart_Liste Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_KS_Kart_Liste)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void KS_Kart_SilCompletedEventHandler(object sender, KS_Kart_SilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KS_Kart_SilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KS_Kart_SilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_Sonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_Sonuc)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void KS_TahsilatCompletedEventHandler(object sender, KS_TahsilatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KS_TahsilatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KS_TahsilatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ST_TP_Islem_Odeme Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ST_TP_Islem_Odeme)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591